services:
  reverse-proxy:
    image: nginx:alpine
    volumes:
      - $PWD/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always

  web-container:
    image: httpd:alpine
    volumes:
      - $PWD/html:/usr/local/apache2/htdocs
    restart: always

